# Author: Gonzalo Ramos Zúñiga
# Since: 2022/12/30

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  # API Gateway
  PortfolioApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowHeaders: "'Content-Type'"
        AllowMethods: "'GET,OPTIONS,PUT'"
        AllowOrigin: "'*'"
      Name: portfolio
      Domain:
        CertificateArn: !Ref PortfolioCertificate
        DomainName: !Sub "api.${DomainName}"
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: !Ref HostedZoneId
        SecurityPolicy: TLS_1_2
      StageName: !Ref Stage
      Variables:
        AWS_LAMBDA_ALIAS: !Ref Stage
  # Certificate Manager
  PortfolioCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions: # DomainName & HostedZoneId required when ValidationMethod = DNS
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      SubjectAlternativeNames:
        - !Sub "*.${DomainName}"
      ValidationMethod: DNS
  # Lambda
  PortfolioFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Stage
      CodeUri: .
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref PortfolioSimpleTable
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Events:
        GetPortfolio:
          Type: Api
          Properties:
            Method: get
            Path: /portfolio
            RestApiId: !Ref PortfolioApi
        PutPortfolio:
          Type: Api
          Properties:
            Method: put
            Path: /portfolio
            RestApiId: !Ref PortfolioApi
      Handler: samportfolio.Application::handleRequest
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PortfolioSimpleTable
      Runtime: java11
      Timeout: 20
  # DynamoDB
  PortfolioSimpleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: key
        Type: String
      TableName: portfolio